# Data Analysis
## Lesson 3 : NumPy and Pandas for 2D Data

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

### Related Questions about NYC subway and weather
> 1. is there correlation in metro usage and rainy days<br>
2. how many people check weather before start of the day<br>
3. seasonal impact on sunrise and sunset<br>
4. average temperature of stations in day<br>
5. min and max temperature of stations<br>

Questions I thought of:
    - What variables are related to subsway ridership?
        - Which stations have the most riders?
        - What are the ridership patterns over time?
        - How does the weather affect ridership?
    - What patterns can I find in the weather?
        - Is the temperature rising throughout the month?
        - How does the weather vary across the city?

In [2]:
df_newyork = pd.read_csv('./csv/nyc_subway_weather.csv')

In [3]:
df_newyork

,UNIT,DATEn,TIMEn,ENTRIESn,EXITSn,ENTRIESn_hourly,EXITSn_hourly,datetime,hour,day_week,...,pressurei,rain,tempi,wspdi,meanprecipi,meanpressurei,meantempi,meanwspdi,weather_lat,weather_lon
0,R003,05-01-11,00:00:00,4388333,2911002,0.0,0.0,2011-05-01 00:00:00,0,6,...,30.22,0,55.9,3.5,0.000000,30.258000,55.980000,7.860000,40.700348,-73.887177
1,R003,05-01-11,04:00:00,4388333,2911002,0.0,0.0,2011-05-01 04:00:00,4,6,...,30.25,0,52.0,3.5,0.000000,30.258000,55.980000,7.860000,40.700348,-73.887177
2,R003,05-01-11,12:00:00,4388333,2911002,0.0,0.0,2011-05-01 12:00:00,12,6,...,30.28,0,62.1,6.9,0.000000,30.258000,55.980000,7.860000,40.700348,-73.887177
3,R003,05-01-11,16:00:00,4388333,2911002,0.0,0.0,2011-05-01 16:00:00,16,6,...,30.26,0,57.9,15.0,0.000000,30.258000,55.980000,7.860000,40.700348,-73.887177
4,R003,05-01-11,20:00:00,4388333,2911002,0.0,0.0,2011-05-01 20:00:00,20,6,...,30.28,0,52.0,10.4,0.000000,30.258000,55.980000,7.860000,40.700348,-73.887177
5,R003,05-02-11,00:00:00,4388348,2911036,15.0,34.0,2011-05-02 00:00:00,0,0,...,30.31,0,50.0,6.9,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
6,R003,05-02-11,04:00:00,5818689,3874767,19.0,40.0,2011-05-02 04:00:00,4,0,...,30.27,0,50.0,4.6,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
7,R003,05-02-11,08:00:00,4388855,2911194,488.0,118.0,2011-05-02 08:00:00,8,0,...,30.30,0,53.1,10.4,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
8,R003,05-02-11,12:00:00,4389345,2911326,490.0,132.0,2011-05-02 12:00:00,12,0,...,30.24,0,57.0,11.5,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
9,R003,05-02-11,16:00:00,4389576,2911558,231.0,232.0,2011-05-02 16:00:00,16,0,...,30.16,0,59.0,11.5,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
10,R003,05-02-11,20:00:00,4389811,2911963,235.0,405.0,2011-05-02 20:00:00,20,0,...,30.15,0,55.9,4.6,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
11,R003,05-03-11,00:00:00,4389885,2912127,74.0,164.0,2011-05-03 00:00:00,0,1,...,30.13,0,54.0,4.6,0.000000,30.048000,58.940000,8.060000,40.700348,-73.887177
12,R003,05-03-11,04:00:00,4389905,2912160,20.0,33.0,2011-05-03 04:00:00,4,1,...,30.11,0,51.8,5.8,0.000000,30.048000,58.940000,8.060000,40.700348,-73.887177
13,R003,05-03-11,12:00:00,4390880,2912394,975.0,234.0,2011-05-03 12:00:00,12,1,...,30.07,0,60.8,9.2,0.000000,30.048000,58.940000,8.060000,40.700348,-73.887177
14,R003,05-03-11,16:00:00,4391147,2912651,267.0,257.0,2011-05-03 16:00:00,16,1,...,29.98,0,66.0,9.2,0.000000,30.048000,58.940000,8.060000,40.700348,-73.887177
15,R003,05-03-11,20:00:00,4391424,2913049,277.0,398.0,2011-05-03 20:00:00,20,1,...,29.95,0,62.1,11.5,0.000000,30.048000,58.940000,8.060000,40.700348,-73.887177
16,R003,05-04-11,00:00:00,4391507,2913223,83.0,174.0,2011-05-04 00:00:00,0,2,...,29.94,1,59.0,9.2,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
17,R003,05-04-11,04:00:00,4391531,2913258,24.0,35.0,2011-05-04 04:00:00,4,2,...,29.91,1,60.1,0.0,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
18,R003,05-04-11,08:00:00,4392063,2913388,532.0,130.0,2011-05-04 08:00:00,8,2,...,29.94,1,55.4,15.0,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
19,R003,05-04-11,12:00:00,4392517,2913495,454.0,107.0,2011-05-04 12:00:00,12,2,...,29.96,1,51.1,11.5,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
20,R003,05-04-11,16:00:00,4392764,2913744,247.0,249.0,2011-05-04 16:00:00,16,2,...,29.96,1,48.0,18.4,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
21,R003,05-04-11,20:00:00,4392984,2914100,220.0,356.0,2011-05-04 20:00:00,20,2,...,30.01,1,50.0,16.1,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
22,R003,05-05-11,00:00:00,4393043,2914284,59.0,184.0,2011-05-05 00:00:00,0,3,...,30.01,0,48.9,16.1,0.000000,29.944000,55.720000,15.220000,40.700348,-73.887177
23,R003,05-05-11,04:00:00,4393062,2914319,19.0,35.0,2011-05-05 04:00:00,4,3,...,29.98,0,48.0,12.7,0.000000,29.944000,55.720000,15.220000,40.700348,-73.887177
24,R003,05-05-11,12:00:00,4394057,2914509,995.0,190.0,2011-05-05 12:00:00,12,3,...,29.91,0,60.8,15.0,0.000000,29.944000,55.720000,15.220000,40.700348,-73.887177
25,R003,05-05-11,16:00:00,4394364,2914754,307.0,245.0,2011-05-05 16:00:00,16,3,...,29.88,0,63.0,19.6,0.000000,29.944000,55.720000,15.220000,40.700348,-73.887177
26,R003,05-05-11,20:00:00,4394592,2915145,228.0,391.0,2011-05-05 20:00:00,20,3,...,29.94,0,57.9,12.7,0.000000,29.944000,55.720000,15.220000,40.700348,-73.887177
27,R003,05-06-11,00:00:00,4394665,2915321,73.0,176.0,2011-05-06 00:00:00,0,4,...,29.97,0,55.0,3.5,0.000000,29.918000,60.580000,11.300000,40.700348,-73.887177
28,R003,05-06-11,04:00:00,4394687,2915369,22.0,48.0,2011-05-06 04:00:00,4,4,...,29.96,0,52.0,8.1,0.000000,29.918000,60.580000,11.300000,40.700348,-73.887177
29,R003,05-06-11,12:00:00,4395657,2915590,970.0,221.0,2011-05-06 12:00:00,12,4,...,29.94,0,68.0,16.1,0.000000,29.918000,60.580000,11.300000,40.700348,-73.887177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42619,R464,05-26-11,16:00:00,419894,95280,0.0,0.0,2011-05-26 16:00:00,16,3,...,29.89,0,69.1,9.2,0.000000,29.922000,66.640000,7.160000,40.660004,-73.844849
42620,R464,05-26-11,20:00:00,419894,95280,0.0,0.0,2011-05-26 20:00:00,20,3,...,29.88,0,66.9,8.1,0.000000,29.922000,66.640000,7.160000,40.660004,-73.844849
42621,R464,05-27-11,00:00:00,419894,95280,0.0,0.0,2011-05-27 00:00:00,0,4,...,29.92,0,66.0,4.6,0.000000,29.948000,69.160000,12.680000,40.660004,-73.844849
42622,R464,05-27-11,04:00:00,419894,95280,0.0,0.0,2011-05-27 04:00:00,4,4,...,29.94,0,64.0,3.5,0.000000,29.948000,69.160000,12.680000,40.660004,-73.844849
42623,R464,05-27-11,12:00:00,419894,95280,0.0,0.0,2011-05-27 12:00:00,12,4,...,29.99,0,73.0,12.7,0.000000,29.948000,69.160000,12.680000,40.660004,-73.844849
42624,R464,05-27-11,16:00:00,419894,95280,0.0,0.0,2011-05-27 16:00:00,16,4,...,29.93,0,75.9,20.7,0.000000,29.948000,69.160000,12.680000,40.660004,-73.844849
42625,R464,05-27-11,20:00:00,419894,95280,0.0,0.0,2011-05-27 20:00:00,20,4,...,29.96,0,66.9,21.9,0.000000,29.948000,69.160000,12.680000,40.660004,-73.844849
42626,R464,05-28-11,00:00:00,419894,95280,0.0,0.0,2011-05-28 00:00:00,0,5,...,30.00,0,66.0,4.6,0.000000,30.032000,69.780000,10.360000,40.660004,-73.844849
42627,R464,05-28-11,04:00:00,419894,95280,0.0,0.0,2011-05-28 04:00:00,4,5,...,30.00,0,64.0,6.9,0.000000,30.032000,69.780000,10.360000,40.660004,-73.844849
42628,R464,05-28-11,12:00:00,419894,95280,0.0,0.0,2011-05-28 12:00:00,12,5,...,30.05,0,77.0,11.5,0.000000,30.032000,69.780000,10.360000,40.660004,-73.844849
42629,R464,05-28-11,16:00:00,419894,95280,0.0,0.0,2011-05-28 16:00:00,16,5,...,30.05,0,73.9,15.0,0.000000,30.032000,69.780000,10.360000,40.660004,-73.844849
42630,R464,05-28-11,20:00:00,419894,95280,0.0,0.0,2011-05-28 20:00:00,20,5,...,30.06,0,68.0,13.8,0.000000,30.032000,69.780000,10.360000,40.660004,-73.844849
42631,R464,05-29-11,00:00:00,419894,95280,0.0,0.0,2011-05-29 00:00:00,0,6,...,30.09,0,66.0,9.2,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42632,R464,05-29-11,04:00:00,419894,95280,0.0,0.0,2011-05-29 04:00:00,4,6,...,30.09,0,64.9,6.9,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42633,R464,05-29-11,08:00:00,129127,35492,0.0,0.0,2011-05-29 08:00:00,8,6,...,30.13,0,66.2,6.9,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42634,R464,05-29-11,12:00:00,419894,95280,0.0,0.0,2011-05-29 12:00:00,12,6,...,30.13,0,75.9,10.4,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42635,R464,05-29-11,16:00:00,419894,95280,0.0,0.0,2011-05-29 16:00:00,16,6,...,30.06,0,75.0,18.4,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42636,R464,05-29-11,20:00:00,419894,95280,0.0,0.0,2011-05-29 20:00:00,20,6,...,30.08,0,70.0,15.0,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42637,R464,05-30-11,00:00:00,419894,95280,0.0,0.0,2011-05-30 00:00:00,0,0,...,30.09,1,64.9,5.8,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42638,R464,05-30-11,04:00:00,419894,95280,0.0,0.0,2011-05-30 04:00:00,4,0,...,30.04,1,66.9,3.5,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42639,R464,05-30-11,08:00:00,129127,35492,0.0,0.0,2011-05-30 08:00:00,8,0,...,30.09,1,72.0,13.8,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42640,R464,05-30-11,12:00:00,419894,95280,0.0,0.0,2011-05-30 12:00:00,12,0,...,30.10,1,82.9,8.1,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42641,R464,05-30-11,16:00:00,419894,95280,0.0,0.0,2011-05-30 16:00:00,16,0,...,30.06,1,82.0,9.2,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42642,R464,05-30-11,20:00:00,419894,95280,0.0,0.0,2011-05-30 20:00:00,20,0,...,30.10,1,73.0,4.6,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42643,R464,05-31-11,00:00:00,419894,95280,0.0,0.0,2011-05-31 00:00:00,0,1,...,30.13,0,72.0,0.0,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849
42644,R464,05-31-11,04:00:00,567311,132804,0.0,0.0,2011-05-31 04:00:00,4,1,...,30.14,0,73.0,6.9,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849
42645,R464,05-31-11,08:00:00,290767,59788,0.0,0.0,2011-05-31 08:00:00,8,1,...,30.19,0,80.1,6.9,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849
42646,R464,05-31-11,12:00:00,419894,95280,0.0,0.0,2011-05-31 12:00:00,12,1,...,30.20,0,81.0,10.4,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849
42647,R464,05-31-11,16:00:00,419894,95280,0.0,0.0,2011-05-31 16:00:00,16,1,...,30.17,0,77.0,13.8,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849
42648,R464,05-31-11,20:00:00,419894,95280,0.0,0.0,2011-05-31 20:00:00,20,1,...,30.18,0,69.1,4.6,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849

### Two-Dimensional NumPy Arrays

In [11]:
import numpy as np

# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

# Change False to True for each block of code to see what it does

# Accessing elements
if False:
    print(ridership[1, 3])
    print(ridership[1:3, 3:5])
    print(ridership[1, :])
    
# Vectorized operations on rows or columns
if True:
    print(ridership[0, :] + ridership[1, :])
    print(ridership[:, 0] + ridership[:, 1])
    
# Vectorized operations on entire arrays
if False:
    a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
    print(a + b)

[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]

In [17]:
# Find the max riders on the first day
max_station = ridership[0,:].argmax()
max_station

# Find the mean riders per day
mean_for_max = ridership[:,max_station].mean()

# Find the mean ridership overall for comparison
overall_mean = ridership.mean()

In [18]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
    '''
    # Find the max riders on the first day
    max_station = ridership[0,:].argmax()

    # Find the mean ridership overall for comparison
    overall_mean = ridership.mean()
    # Find the mean riders per day
    mean_for_max = ridership[:,max_station].mean()
    
    return (overall_mean, mean_for_max)

In [19]:
mean_riders_for_max_station(ridership)

(2342.5999999999999, 3239.9000000000001)

### NumPy Axis
![title](./picture/numpy_axis.png)

In [40]:
# Change False to True for this block of code to see what it does

# NumPy axis argument
if True:
    a = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
    
    print(a.sum())
    print(a.sum(axis=0))
    print(a.sum(axis=1))
    
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

def min_and_max_riders_per_day(ridership):
    '''
    Fill in this function. First, for each subway station, calculate the
    mean ridership per day. Then, out of all the subway stations, return the
    maximum and minimum of these values. That is, find the maximum
    mean-ridership-per-day and the minimum mean-ridership-per-day for any
    subway station.
    '''
    station_mean_per_day = ridership.mean(axis=0)
    print(station_mean_per_day)
    
    max_mean_station = station_mean_per_day.max()
    min_mean_station = station_mean_per_day.min()
    
    print('max : %8.4f, min : %8.4f' % (max_mean_station, min_mean_station))
    max_daily_ridership = max_mean_station     # Replace this with your code
    min_daily_ridership = min_mean_station     # Replace this with your code
    
    return (max_daily_ridership, min_daily_ridership)

45
[12 15 18]
[ 6 15 24]

In [41]:
min_and_max_riders_per_day(ridership)

[ 1071.2  2814.9  2718.8  3239.9  1868.2]
max : 3239.9000, min : 1071.2000

(3239.9000000000001, 1071.2)

### NumPy and Pandas Data Types
- NumPy는 자료형이 변환되지만, Pandas는 고유의 자료형이 컬럼별로 유지된다.

In [43]:
enrollments_df = pd.DataFrame({
    'account_key':[448,448,448,448,448],
    'status':['canceled','canceled','canceled','canceled','canceled'],
    'join_date':['2014-11-10','2014-11-05','2015-01-27','2014-11-10','2015-03-10'],
    'days_to_cancel':[65,5,0,0,np.nan],
    'is_udacity':[True,True,True,True,True]
})

enrollments_df

   account_key  days_to_cancel is_udacity   join_date    status
0          448            65.0       True  2014-11-10  canceled
1          448             5.0       True  2014-11-05  canceled
2          448             0.0       True  2015-01-27  canceled
3          448             0.0       True  2014-11-10  canceled
4          448             NaN       True  2015-03-10  canceled

In [44]:
enrollments_df.mean()

account_key       448.0
days_to_cancel     17.5
is_udacity          1.0
dtype: float64

In [45]:
enrollments_df.mean(axis=1)

0    171.333333
1    151.333333
2    149.666667
3    149.666667
4    224.500000
dtype: float64

### Accessing Elements of a DataFrame

In [58]:
# Subway ridership for 5 stations on 10 different days
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)

# Change False to True for each block of code to see what it does

# DataFrame creation
if False:
    # You can create a DataFrame out of a dictionary mapping column names to values
    df_1 = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
    print(df_1)

    # You can also use a list of lists or a 2D NumPy array
    df_2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns=['A', 'B', 'C'])
    print(df_2)
   

# Accessing elements
if False:
    print(ridership_df.iloc[0])
    print(ridership_df.loc['05-05-11'])
    print(ridership_df['R003'])
    print(ridership_df.iloc[1, 3])
    
# Accessing multiple rows
if False:
    print(ridership_df.iloc[1:4])
    
# Accessing multiple columns
if False:
    print(ridership_df[['R003', 'R005']])
    
# Pandas axis
if False:
    df = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
    print(df.sum())
    print(df.sum(axis=1))
    print(df.values.sum())
    
max_station = ridership_df.loc['05-01-11'].argmax()
max_station

mean_for_max = ridership_df[max_station].mean()

overall_mean = ridership_df.values.mean()

2342.5999999999999

In [64]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    This is the same as a previous exercise, but this time the
    input is a Pandas DataFrame rather than a 2D NumPy array.
    '''
    # find the station with the maximun riders on the first day
    # max_station = ridership.loc['05-01-11'].argmax()
    max_station = ridership.iloc[0].argmax()
    max_station

    overall_mean = ridership.values.mean() # Replace this with your code
    mean_for_max = ridership[max_station].mean() # Replace this with your code
    
    return (overall_mean, mean_for_max)

In [65]:
mean_riders_for_max_station(ridership_df)

(2342.5999999999999, 3239.9)